config/routes.rb
Rails.application.routes.draw do

  concern :sortable do
    put 'sort', on: :collection
  end

  # Ops

  namespace :ops, path: '/', constraints: { subdomain: 'ops' } do
    mount Coupons::Engine => '/', as: 'coupons_engine'

    root to: redirect('/instructors')

    resources :instructors, only: [:index, :show, :create, :destroy] do
      put :assume, on: :member
      put :seed_competition, on: :member
    end

    resources :students, only: [:index] do
      put :assume, on: :member
    end

    resources :competitions, only: [:index, :show, :destroy] do
      put :seed_student, on: :member
    end

  end


  # Instructors

  namespace :admin, path: '/', constraints: { subdomain: 'admin' } do

    root to: redirect('/competitions')

    # Authentication
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'login', to: 'sessions#new', as: 'login'
    get 'login_with_password', to: 'sessions#new_with_password', as: 'login_with_password'
    post 'session', to: 'sessions#create', as: 'session'

    # Registration
    get 'signup', to: 'registrations#new', as: 'signup'
    get 'signup_with_password', to: 'registrations#new_with_password', as: 'signup_with_password'
    post 'registration', to: 'registrations#create', as: 'registration'

    # LinkedIn OAuth
    get 'auth/linkedin/callback',   to: 'linkedin_authentications#create'
    # If something goes wrong during linked in authentication (e.g. the user cancels). We are redirected to
    # "/auth/failure?strategy=linkedin".
    get 'auth/failure', to: 'linkedin_authentications#failure', constraints: -> (req) { req.params[:strategy] == 'linkedin' }

    resources :competitions do
      get 'leaderboard', on: :member
      get 'history', on: :member
      get 'download_coursepack', on: :collection
    end

    resources :knowledgebase, only: [:index, :show]

    resources :teams, only: :show do
      resources :team_comments
    end

    resources :team_learning_resources, only: :show

    resources :learning_resources, except: :destroy, concerns: :sortable do
      put 'publish', on: :member
      put 'unpublish', on: :member

      resources :tasks, controller: 'learning_resource_tasks', concerns: :sortable
      resources :questions, controller: 'learning_resource_questions', concerns: :sortable

    end

  end


  # Students

  namespace :student, path: '/', as: nil, constraints: { subdomain: 'app' } do

    root to: redirect('/team')

    # Authentication
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'login', to: 'sessions#new', as: 'login'
    get 'login_with_password', to: 'sessions#new_with_password', as: 'login_with_password'
    post 'session', to: 'sessions#create', as: 'session'

    # Registration
    get '/join/:token', to: 'registrations#new', as: 'join'
    get '/join_with_password/:token', to: 'registrations#new_with_password', as: 'join_with_password'
    post 'registration', to: 'registrations#create', as: 'registration'

    # LinkedIn OAuth
    get 'auth/linkedin/callback',   to: 'linkedin_authentications#create'
    # If something goes wrong during linked in authentication (e.g. the user cancels). We are redirected to
    # "/auth/failure?strategy=linkedin".
    get 'auth/failure', to: 'linkedin_authentications#failure', constraints: -> (req) { req.params[:strategy] == 'linkedin' }

    # Shopify OAuth
    get 'auth/shopify/callback', to: 'shops#auth_success'
    # Omniauth failures not handled by authentication must be from shopify
    # (invalid shopify urls?).
    get 'auth/failure', to: 'shops#auth_failure'
    get 'shop_confirmation_callback', to: 'shops#confirmation_callback'

    resource :team do
      resource :membership, only: [:new, :create, :destroy]
    end

    resources :tasks, only: [:index, :update]

    resources :team_comments

    resources :team_learning_resources, only: [:show, :update] do
      resources :tasks, controller: 'team_learning_resource_tasks', only: [:index, :update]
      resources :questions, controller: 'team_learning_resource_questions', only: [:index, :update]
    end

    resource :shop

    resource :leaderboard, controller: 'competitions' do
      get 'history', on: :collection
    end

    resource 'financials', only: [:show, :update]

  end

  # Global

  resources :shopify_webhooks, only: :create

end

app/models/learning_resource.rb
# == Schema Information
#
# Table name: learning_resources
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  body          :text
#  video_url     :string(255)
#  instructor_id :integer          indexed
#  order         :integer          default("0")
#  is_template   :boolean          default("false")
#  created_at    :datetime
#  updated_at    :datetime
#  is_published  :boolean          default("false")
#  description   :text
#  is_deleted    :boolean          default("false")
#
# Indexes
#
#  index_learning_resources_on_instructor_id  (instructor_id)
#

class LearningResource < ActiveRecord::Base

  include Sortable

  belongs_to :instructor

  has_many :questions, class_name: 'LearningResourceQuestion', dependent: :destroy
  has_many :tasks, class_name: 'LearningResourceTask', dependent: :destroy

  validates :title,
            presence: true

  validates :body,
            presence: true

  validate :require_valid_youtube_video_url

  scope :templates, -> { where(is_template: true) }

  scope :published, -> { where(is_published: true) }

  scope :non_deleted, -> { where(is_deleted: false) }

  def publish
    update!(is_published: true)
  end

  def unpublish
    update!(is_published: false)
  end

  def video_embed_url
    video_url.presence && Youtube::Video.parse(video_url).embed_url
  end

  def duplicate_for(instructor)
    dup = LearningResource.create!( instructor: instructor,
                                    title: title,
                                    body: body,
                                    video_url: video_url,
                                    is_published: true,
                                    order: order )
    # Duplicate questions.
    questions.each do |q|
      dup.questions.create!( title: q.title,
                             order: q.order )
    end

    # Duplicate tasks.
    tasks.each do |t|
      dup.tasks.create!( title: t.title,
                         order: t.order )
    end

    dup
  end

  def duplicate_for_team(team)
    dup = TeamLearningResource.create!(
      team: team,
      title: title,
      body: body,
      video_url: video_url,
      order: order
    )

    # Duplicate questions.
    questions.each do |q|
      dup.questions.create!( title: q.title,
                             order: q.order )
    end

    # Duplicate tasks.
    tasks.each do |t|
      dup.tasks.create!( title: t.title,
                         order: t.order )
    end

    dup
  end

  protected

    # Requires the url be a valid youtube url.
    #
    def require_valid_youtube_video_url
      return if video_url.blank?
      return if Youtube::Video.valid?(video_url)

      errors.add(:video_url, 'must be a youtube video URL')
    end

end

app/controllers/admin/learning_resources_controller.rb
class Admin::LearningResourcesController < AdminController

  before_action :require_admin

  def index
    respond_to do |format|
      format.json { render json: current_admin.learning_resources.non_deleted.sorted }
      format.html {}
    end
  end

  def new
    @resource = current_admin.learning_resources.build
  end

  def create
    @resource = current_admin.learning_resources.build_at_end(learning_resource_params)

    if @resource.save
      redirect_to [:admin, @resource], notice: 'Learning resource successfully created.'
    else
      render :new
    end
  end

  def show
    @resource = find_learning_resource
  end

  def edit
    @resource = find_learning_resource
  end

  def update
    @resource = find_learning_resource

    if @resource.update(learning_resource_params)
      redirect_to [:admin, @resource], notice: 'Learning resource successfully updated.'
    else
      render :edit
    end
  end

  def publish
    resource = find_learning_resource
    resource.publish
    head :ok
  end

  def unpublish
    resource = find_learning_resource
    resource.unpublish
    head :ok
  end

  def sort
    current_admin.learning_resources.sort(params[:ordered_ids])
    head :ok
  end

  private

    def find_learning_resource
      current_admin.learning_resources.find(params[:id])
    end

    def learning_resource_params
      params.require(:learning_resource).permit(:title, :body, :video_url)
    end

end

app/views/admin/learning_resources/_form_fields.html.slim
= render 'application/errors', resource: @resource

.row
  .large-12.columns
    label
      | Title
      = f.text_field :title, required: true

  .large-12.columns
    label
      | Video URL
      = f.text_field :video_url, placeholder: 'Enter a youtube embed URL (e.g. http://youtu.be/7N8b3NZSJoY)'

  .large-12.columns
    label
      | Body
      = f.text_area :body, rows: 8

app/views/admin/learning_resources/edit.html.slim
#learning-resources-edit.row

  .breadcrumb-text
    ul
      li= link_to 'Learning Resources', admin_learning_resources_path
      li= link_to @resource.title, [:admin, @resource]

  h1.page-header Edit #{@resource.title}

  = form_for [:admin, @resource] do |f|

    = render 'form_fields', f: f

    = link_to 'Cancel', [:admin, @resource], class: 'button secondary'
    | &nbsp;
    = f.submit 'Save', class: 'button'

app/views/admin/learning_resources/index.html.slim
#learning-resources-index.row[ng-app="learningResourceListApp" ng-controller="AppCtrl as vm" ng-cloak]

  .intro.panel
    h3 Setup your Competition
    p Learning Resources are the framework on which your competition is built. They provide education, support and the outline for your students' experience.  You can customize any of our built in resources or unpublish them as necessary.  You can also build your own custom learning resources.

    p Remember that when you create a competition it will import all of the active learning resources and outcomes that you select here.  Any later edits you make to the learning resources will not be reflected in your live competitions.

    p
      ' Watch the
      a[href='#' data-reveal-id='overview-modal'] getting started overview video
      '  to learn how to setup learning resources.

  h3.page-header
    aside
      = link_to 'New learning resource', new_admin_learning_resource_path, class: 'button'
    | My Learning Resources

  ul.learning-resource-list[ui-sortable="vm.sortableOptions" ng-model="vm.resources"]
    li.learning-resource-item[ng-repeat="resource in vm.resources"]
      a.learning-resource-link.clearfix[ng-href="{{resource.url}}"]
        .handle
          i.fa.fa-bars

        h4.title
          | {{ resource.title }}

        .switch.small.round
          input[id="toggle-resource-{{resource.id}}" type='checkbox' ng-model="resource.is_published" ng-change="vm.publishToggled(resource)"]
          label[for="toggle-resource-{{resource.id}}"]

        .pull-right

          .label.radius[ng-show="resource.is_published"] Published
          .label.secondary.radius[ng-hide="resource.is_published"] Draft

    br/

    #overview-modal.reveal-modal[data-reveal]
      h5 Venture Challenge Overview
      .flex-video
        iframe[src="https://player.vimeo.com/video/126895025" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen]


      a.close-reveal-modal &#215;

app/views/admin/learning_resources/new.html.slim
#learning-resources-new.row

  nav.breadcrumbs
    = link_to 'Learning Resources', admin_learning_resources_path
    a.current[href='#'] New

  .panel

    .panel-header
      h1 New learning resource

    = form_for [:admin, @resource] do |f|

      = render 'form_fields', f: f

      = link_to 'Cancel', admin_learning_resources_path, class: 'button secondary'
      | &nbsp;
      = f.submit 'Create learning resource', class: 'button success'

app/views/admin/learning_resources/show.html.slim
#learning-resources-show.row[ng-app="learningResourceApp" ng-cloak]

  .breadcrumb-text
    ul
      li= link_to 'Learning Resources', admin_learning_resources_path

  h1.page-header
    aside
      = link_to 'Edit', [:edit, :admin, @resource], class: 'button'
    = @resource.title

  .row

    .large-6.columns.body

      - if @resource.video_embed_url
        iframe[width="410" height="315" src="#{@resource.video_embed_url}" frameborder="0" allowfullscreen]

      = @resource.body.html_safe

    .large-6.columns

      .tasks.panel[ng-controller="TasksCtrl as vm"]

        h2 Tasks

        p[ng-show="vm.tasksEmpty()"] No tasks yet&hellip;

        ul[ui-sortable="vm.sortableOptions" ng-model="vm.tasks"]
          li.task[ng-repeat="task in vm.tasks"]
            .task-handle
              i.fa.fa-bars
            .task-title
              | {{ task.title }}
            a.task-delete[ng-click="vm.removeTask(task)"]
              i.fa.fa-trash

        .row
          form[ng-submit="vm.addTask()"]
            .large-10.columns
              input[type='text' ng-model="vm.newTitle" placeholder="Add a task…"]
            .large-2.columns.left
              button[type="submit"] Add

      .questions.panel[ng-controller="QuestionsCtrl as vm"]

        h2 Questions

        p[ng-show="vm.questionsEmpty()"] No questions yet&hellip;

        ul[ui-sortable="vm.sortableOptions" ng-model="vm.questions"]
          li.question[ng-repeat="question in vm.questions"]
            .question-handle
              i.fa.fa-bars
            .question-title
              | {{ question.title }}
            a.question-delete[ng-click="vm.removeQuestion(question)"]
              i.fa.fa-trash

        .row
          form[ng-submit="vm.addQuestion()"]
            .large-10.columns
              input[type='text' ng-model="vm.newTitle" placeholder="Add a question…"]
            .large-2.columns.left
              button[type="submit"] Add